server:
  port: ${PORT:5000}

base-url: /api
rollbar_token: ${ROLLBAR_TOKEN:b6aa877be0aa4e198d020e890f0ae2d8}

jwt:
  secret: ${JWT_SECRET:secret}

spring:

  mail:
    host: ${HOST_ENV}
    port: ${PORT_ENV}
    username: ${USERNAME_ENV}
    password: ${PASSWORD_ENV}
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: hrManager

  profiles:
    active: ${APP_ENV:dev}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hidden-method:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate


springdoc:
  api-docs:
    path:

google:
  clientId: ${GOOGLE_CLIENT_ID:}
  redirect-url: ${GOOGLE_REDIRECT_URL:}
